volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.3-alpine
    container_name: foodgram-db
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: ${DOCKER_USERNAME}/foodgram-backend:latest
    container_name: foodgram-backend
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: ${DOCKER_USERNAME}/foodgram-frontend:latest
    container_name: foodgram-front
    restart: "no"
    env_file:
      - .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: ${DOCKER_USERNAME}/foodgram-gateway:latest
    container_name: foodgram-gateway
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "${FOODGRAM_PORT:-8080}:80"
    volumes:
      - static:/staticfiles
      - media:/media
